#!/bin/bash

GUEST=test
CMD="$@"

while true ; do
	res=$(virsh qemu-agent-command $GUEST '{"execute":"guest-ping"}' &2>/dev/null)
	if [ "$(echo $res | jq -r '.return')" == '{}' ] ; then
		break
	else
		sleep 0.5	
	fi	
done

res=$(virsh qemu-agent-command $GUEST "{
  \"execute\": \"guest-exec\",
  \"arguments\": {
    \"path\": \"/bin/bash\",
    \"arg\": [\"-c\", \"$CMD\"],
    \"capture-output\": true
  }
}")

pid=$(echo $res |jq .return.pid)
finished=false
while ! $finished ; do
	res=$(virsh qemu-agent-command $GUEST "{
	  \"execute\": \"guest-exec-status\",
	  \"arguments\": {
	    \"pid\": $pid
	  }
	}")
	if $(echo $res | jq -r '.return["exited"]') == true ; then
		finished=true
	else
		sleep 0.5	
	fi	
done

decoded=$(echo $res | jq -r '.return["out-data"]')
if [ $decoded != null ]; then 
	echo $decoded | base64 -d
fi
decoded=$(echo $res | jq -r '.return["err-data"]')
if [ $decoded != null ]; then 
	echo $decoded | base64 -d
fi
exit_code=$(echo $res | jq -r '.return["exitcode"]')
exit $exit_code
